version: 3

tasks:
  build:
    desc: Build
    cmds:
      - go mod download
      - go mod tidy
      - go build ./...

  dependencyUpdates:
    desc: Show dependency updates
    cmds:
      - go list -u -m -json all | go-mod-outdated -update -direct

  mingo:
    cmds:
      - mise exec go@1.25.0 -- mise install 'go:github.com/bobg/mingo/cmd/mingo@0.14.0'
      - mise exec 'go:github.com/bobg/mingo/cmd/mingo@0.14.0' -- mingo -tests -v
